# This file configures how Replit deploys your project
run = "npm run start"

# Ensure these secrets are passed to the deployment
[env]
OPENAI_ASSISTANT_ID = "$OPENAI_ASSISTANT_ID"
OPENAI_API_KEY = "$OPENAI_API_KEY"
BIBLE_API_KEY = "$BIBLE_API_KEY"
NODE_ENV = "production"

# Configure the deployment
[deployment]
ignorePorts = false
deploymentTarget = "cloudrun"
deploymentId = "littlegabriel"

# Build configuration
build.buildCommand = "bash deploy-prep.sh && next build"
build.containerCommand = "npm run start"