#!/bin/bash
# Startup script for LittleGabriel deployment
# Generated by final-deployment-fix.js

# Ensure environment variables are properly set
export NODE_ENV=production
export OPENAI_ASSISTANT_ID=asst_BpFiJmyhoHFYUj5ooLEoHEX2

# Start the Next.js server
echo "Starting LittleGabriel production server..."
echo "Environment: NODE_ENV=$NODE_ENV"
echo "OpenAI Assistant ID: $OPENAI_ASSISTANT_ID"

# Use the standalone server if available
if [ -d ".next/standalone" ]; then
  echo "Using standalone server..."
  node .next/standalone/server.js
else
  echo "Using next start..."
  npx next start -p 3000
fi
